### PR TITLE
Fix owner calculation.

### PR DESCRIPTION
**Pull request by davidlehn**
I'm unsure what the logic here should be.  The identity check would crash when logged in and using the newer account system.  The agent calculation also was perhaps incorrect?  Please review.

### CODE REVIEW

**Comment by dlongley** [comment]
If this is correct, we should get it into a release.

**Comment by mattcollier** [comment]
Is it cleaner just to make a breaking release here and drop `identity` support all together?

**Comment by aljones15** [comment]
> Is it cleaner just to make a breaking release here and drop `identity` support all together?

Taken how prevelant `bedrock-identity` is https://github.com/search?q=in%3Afile+bedrock-identity&type=Code

that is 216 references found to it in public repos, backwards compatibility for now is probably a better idea.

**Comment by davidlehn** [comment]
I'm still unsure on what the right approach is here.  If we could simplify by dropping older support, that'd be great.  I may have tried and failed to do that when I wrote this patch.  But things may have since changed.  Some variant of this does seem to be required though.

**Comment by aljones15** [comment]
> I'm still unsure on what the right approach is here. If we could simplify by dropping older support, that'd be great. I may have tried and failed to do that when I wrote this patch. But things may have since changed. Some variant of this does seem to be required though.

Additionally the docs seem to suggest that req.user.actor > req.user.account.

Anyways I have a branch that is working with all of the latest stuff.

**Comment by mattcollier** [comment]
@aljones15 @davidlehn can either of you speak to what needs to be done with this and any subsidiary PRs?

**Comment by davidlehn** [comment]
@mattcollier I'm not sure of the current state of things.  Progress has been made elsewhere related to identity/account issues. 
 Looks like #fix-owner-fix branch had further changes (with backwards compat?), and PR #30 went even further and just removed identity support.  Was that PR close to done?  I don't know how those changes effect use in other libs or apps.

**Comment by aljones15** [comment]
@mattcollier @davidlehn I will test this with the post @JSAssassin non-bedrock-identity stuff this coming week. One minor issue: I believe I went with `req.user.account` when removing bedrock-identity and I believe the final solution was to move to `req.user.actor` over from whatever deprecated identity library was involved in setting it.

**Pull request merged**
