### PR TITLE
Update tests.

### PR DESCRIPTION
**Pull request by davidlehn**
- Use new bedrock@2+ style.
- Update dependencies.

This doesn't pass yet.  bedrock-did-client isn't updated to new document loader pattern.  Unsure what the plan is related to that.

### CODE REVIEW

**Comment by mattcollier** [comment]
@davidlehn bedrock-did-client needs to be eliminated if possible.  functionality moved into web-ledger-client and did-veres-one etc.

**Comment by davidlehn** [comment]
I removed it.  Did some more updates.  Mock data failure now.  WIP.

**Comment by mattcollier** [comment]
I had some commits that focused on updating to latest bedrock-account apis that I added here.

First failure in test suite is because all jsonld-signature calls need to be updated to 4.x.

**Comment by aljones15** [comment]
just a small note: working on this branch so that I can use the updated tests in a branch that removes `bedrock-identity` entirely.

**Comment by aljones15** [comment]
Just for the record this PR https://github.com/digitalbazaar/bedrock-ledger-agent/pull/35 finishes the work started here. It also needs really needs to be reviewed.

**Comment by mattcollier** [comment]
@aljones15 your last comment here says that this PR was replaced by #35.  Does that mean that this PR can be close and the branch deleted?

**Comment by aljones15** [comment]
@mattcollier yes it is safe to close this PR now. Sorry about the wait. @davidlehn THANKS for all the work here.

**Pull request closed without merging**
